"""
MikroTik RouterOS configuration generator.

Updated based on DC Lawn Foley deployment learnings.
Generates production-ready .rsc scripts that work on factory-reset devices.
"""

from typing import Dict, List
from pathlib import Path
import sys

# Add parent directories to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from vendors.base import VendorGenerator
from core.models import NetworkConfig
from core.validators import IPValidator


class MikroTikGenerator(VendorGenerator):
    """MikroTik RouterOS script generator"""

    vendor_name = "mikrotik"
    supported_features = [
        "routing", "firewall", "nat", "vpn_ipsec", "vpn_wireguard",
        "wireless_legacy", "wireless_wifi6", "vlan", "dhcp", "qos"
    ]

    def validate_config(self, config: NetworkConfig) -> List[str]:
        """MikroTik-specific validation"""
        errors = []

        # Validate required fields
        if config.wan and config.wan.mode == "static":
            if not config.wan.ip:
                errors.append("WAN static mode requires IP address")
            if not config.wan.gateway:
                errors.append("WAN static mode requires gateway")

        if config.lan and config.lan.dhcp and config.lan.dhcp.enabled:
            if not config.lan.dhcp.pool_start or not config.lan.dhcp.pool_end:
                errors.append("DHCP requires pool_start and pool_end")

        return errors

    def generate_config(self, config: NetworkConfig) -> Dict[str, str]:
        """Generate RouterOS .rsc scripts"""
        scripts = {}

        # Generate main router script
        if config.deployment_type.value in ['router_only', 'router_and_ap']:
            scripts["router.rsc"] = self._generate_router_script(config)

        # Generate wireless script if needed
        if config.wireless and config.deployment_type.value in ['ap_only', 'router_and_ap']:
            scripts["wireless.rsc"] = self._generate_wireless_script(config)

        return scripts

    def _generate_router_script(self, config: NetworkConfig) -> str:
        """Generate main router configuration - production ready"""
        lines = []
        mikrotik_cfg = config.mikrotik_config or {}

        # Get configuration options with defaults
        lan_ports = mikrotik_cfg.get('lan_ports', ['ether2', 'ether3', 'ether4', 'ether5', 'ether6', 'ether7', 'ether8', 'ether9', 'ether10'])
        timezone = mikrotik_cfg.get('timezone', 'America/Chicago')
        enable_wan_winbox = mikrotik_cfg.get('enable_wan_winbox', True)
        enable_wan_ssh = mikrotik_cfg.get('enable_wan_ssh', False)
        enable_mac_discovery_lan = mikrotik_cfg.get('enable_mac_discovery_lan', True)
        bridge_name = config.lan.interface if config.lan else 'bridge-lan'

        # ============================================================
        # HEADER
        # ============================================================
        lines.append(f"# ===== {config.customer.name} | {config.customer.site} | {config.device_model} =====")
        lines.append(f"# Generated by OberaConnect Network Config Builder")
        lines.append(f"# Vendor: MikroTik RouterOS")
        if config.wan and config.wan.ip:
            lines.append(f"# WAN: {config.wan.ip}/{config.wan.netmask}")
        if config.lan and config.lan.ip:
            lines.append(f"# LAN: {config.lan.ip}/{config.lan.netmask}")
        lines.append("")

        # ============================================================
        # SYSTEM CONFIGURATION
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# SYSTEM CONFIGURATION")
        lines.append("# " + "=" * 60)

        # System identity - use customer name formatted for hostname
        hostname = config.customer.name.replace(" ", "-")
        lines.append(f'/system identity set name="{hostname}"')
        lines.append(f'/system clock set time-zone-name={timezone}')
        lines.append("")

        # ============================================================
        # REMOVE ETHER1 FROM DEFAULT BRIDGE (Critical for WAN)
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# REMOVE ETHER1 FROM DEFAULT BRIDGE (Required for WAN)")
        lines.append("# " + "=" * 60)
        lines.append(':do { /interface bridge port remove [find interface=ether1] } on-error={}')
        lines.append(':do { /ip dhcp-client remove [find] } on-error={}')
        lines.append("")

        # ============================================================
        # WAN CONFIGURATION
        # ============================================================
        if config.wan:
            lines.append("# " + "=" * 60)
            lines.append("# WAN CONFIGURATION")
            lines.append("# " + "=" * 60)
            if config.wan.mode == "static":
                comment = config.customer.notes or "WAN"
                lines.append(f'/ip address add address={config.wan.ip}/{config.wan.netmask} interface={config.wan.interface} comment="{comment}"')
                lines.append(f'/ip route add gateway={config.wan.gateway} comment="Default Gateway"')
            elif config.wan.mode == "dhcp":
                lines.append(f'/ip dhcp-client add interface={config.wan.interface} disabled=no')
            lines.append("")

        # ============================================================
        # LAN CONFIGURATION
        # ============================================================
        if config.lan:
            lines.append("# " + "=" * 60)
            lines.append("# LAN CONFIGURATION")
            lines.append("# " + "=" * 60)

            # Create bridge if it doesn't use the default
            if bridge_name != 'bridgeLocal':
                lines.append(f':do {{ /interface bridge add name={bridge_name} comment="LAN Bridge" }} on-error={{}}')

            # Add LAN ports to bridge with error handling
            lines.append("")
            lines.append("# Add LAN ports to bridge")
            for port in lan_ports:
                lines.append(f':do {{ /interface bridge port add bridge={bridge_name} interface={port} }} on-error={{}}')

            # Also try to add SFP port
            lines.append(':do { /interface bridge port add bridge=' + bridge_name + ' interface=sfp-sfpplus1 } on-error={}')

            lines.append("")
            lines.append("# LAN IP Address")
            lines.append(f'/ip address add address={config.lan.ip}/{config.lan.netmask} interface={bridge_name} comment="LAN Gateway"')
            lines.append("")

        # ============================================================
        # DNS CONFIGURATION
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# DNS CONFIGURATION")
        lines.append("# " + "=" * 60)

        dns_servers = []
        if config.wan and config.wan.dns:
            dns_servers = config.wan.dns
        elif config.lan and config.lan.dhcp and config.lan.dhcp.dns_servers:
            dns_servers = config.lan.dhcp.dns_servers
        else:
            dns_servers = ["8.8.8.8", "8.8.4.4"]

        dns_str = ",".join(dns_servers)
        lines.append(f'/ip dns set servers={dns_str} allow-remote-requests=yes')
        lines.append("")

        # ============================================================
        # DHCP SERVER
        # ============================================================
        if config.lan and config.lan.dhcp and config.lan.dhcp.enabled:
            lines.append("# " + "=" * 60)
            lines.append("# DHCP SERVER")
            lines.append("# " + "=" * 60)

            lines.append(f'/ip pool add name=lan-pool ranges={config.lan.dhcp.pool_start}-{config.lan.dhcp.pool_end}')
            lines.append(f'/ip dhcp-server add name=lan-dhcp interface={bridge_name} address-pool=lan-pool lease-time={config.lan.dhcp.lease_time} disabled=no')

            # Calculate network address from LAN IP
            lan_ip_parts = config.lan.ip.rsplit('.', 1)
            network_addr = lan_ip_parts[0] + '.0'

            dhcp_dns = ",".join(config.lan.dhcp.dns_servers) if config.lan.dhcp.dns_servers else dns_str
            lines.append(f'/ip dhcp-server network add address={network_addr}/{config.lan.netmask} gateway={config.lan.ip} dns-server={dhcp_dns}')
            lines.append("")

        # ============================================================
        # NAT (MASQUERADE)
        # ============================================================
        if config.wan and config.lan:
            lines.append("# " + "=" * 60)
            lines.append("# NAT (MASQUERADE)")
            lines.append("# " + "=" * 60)
            lines.append(f'/ip firewall nat add chain=srcnat out-interface={config.wan.interface} action=masquerade comment="NAT LAN to WAN"')
            lines.append("")

        # ============================================================
        # FIREWALL - INPUT CHAIN
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# FIREWALL - INPUT CHAIN (Protect Router)")
        lines.append("# " + "=" * 60)
        lines.append('/ip firewall filter add chain=input connection-state=established,related action=accept comment="Allow established/related"')
        lines.append('/ip firewall filter add chain=input connection-state=invalid action=drop comment="Drop invalid"')
        lines.append(f'/ip firewall filter add chain=input in-interface={bridge_name} action=accept comment="Allow LAN to router"')

        if config.wan:
            lines.append(f'/ip firewall filter add chain=input in-interface={config.wan.interface} protocol=icmp action=accept comment="Allow WAN ping"')

            if enable_wan_winbox:
                lines.append(f'/ip firewall filter add chain=input in-interface={config.wan.interface} protocol=tcp dst-port=8291 action=accept comment="Allow WAN Winbox"')

            if enable_wan_ssh:
                lines.append(f'/ip firewall filter add chain=input in-interface={config.wan.interface} protocol=tcp dst-port=22 action=accept comment="Allow WAN SSH"')

            lines.append(f'/ip firewall filter add chain=input in-interface={config.wan.interface} action=drop comment="Drop all other WAN input"')
        lines.append("")

        # ============================================================
        # FIREWALL - FORWARD CHAIN
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# FIREWALL - FORWARD CHAIN (Protect LAN)")
        lines.append("# " + "=" * 60)
        lines.append('/ip firewall filter add chain=forward connection-state=established,related action=accept comment="Allow established/related"')
        lines.append('/ip firewall filter add chain=forward connection-state=invalid action=drop comment="Drop invalid"')
        lines.append(f'/ip firewall filter add chain=forward in-interface={bridge_name} action=accept comment="Allow LAN outbound"')

        if config.wan:
            lines.append(f'/ip firewall filter add chain=forward in-interface={config.wan.interface} connection-state=new action=drop comment="Block unsolicited WAN inbound"')
        lines.append("")

        # ============================================================
        # PORT FORWARDING
        # ============================================================
        if config.port_forwards:
            lines.append("# " + "=" * 60)
            lines.append("# PORT FORWARDING")
            lines.append("# " + "=" * 60)
            for pf in config.port_forwards:
                if pf.enabled:
                    lines.append(f'/ip firewall nat add chain=dstnat in-interface={config.wan.interface} protocol={pf.protocol} dst-port={pf.external_port} action=dst-nat to-addresses={pf.internal_ip} to-ports={pf.internal_port} comment="{pf.name}"')
                    # Add forward rule before the drop rule
                    lines.append(f'/ip firewall filter add chain=forward in-interface={config.wan.interface} protocol={pf.protocol} dst-address={pf.internal_ip} dst-port={pf.internal_port} connection-nat-state=dstnat action=accept place-before=[find comment="Block unsolicited WAN inbound"] comment="Allow {pf.name}"')
            lines.append("")

        # ============================================================
        # VLANS
        # ============================================================
        if config.vlans:
            lines.append("# " + "=" * 60)
            lines.append("# VLAN CONFIGURATION")
            lines.append("# " + "=" * 60)
            for vlan in config.vlans:
                lines.append(f'/interface vlan add name=vlan{vlan.id} vlan-id={vlan.id} interface={bridge_name} comment="{vlan.name}"')

                # VLAN IP address
                subnet_parts = vlan.subnet.split('/')
                if len(subnet_parts) == 2:
                    vlan_ip = subnet_parts[0].rsplit('.', 1)[0] + '.1'
                    lines.append(f'/ip address add address={vlan_ip}/{subnet_parts[1]} interface=vlan{vlan.id}')

                # VLAN DHCP
                if vlan.dhcp and vlan.dhcp_config:
                    lines.append(f'/ip pool add name=vlan{vlan.id}-pool ranges={vlan.dhcp_config.pool_start}-{vlan.dhcp_config.pool_end}')
                    lines.append(f'/ip dhcp-server add name=vlan{vlan.id}-dhcp interface=vlan{vlan.id} address-pool=vlan{vlan.id}-pool lease-time={vlan.dhcp_config.lease_time} disabled=no')
                    lines.append(f'/ip dhcp-server network add address={vlan.subnet} gateway={vlan_ip}')
            lines.append("")

        # ============================================================
        # SERVICES
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# SERVICES")
        lines.append("# " + "=" * 60)

        # Winbox - always enabled
        lines.append('/ip service set winbox disabled=no')

        # SSH - LAN only unless WAN SSH enabled
        if config.lan:
            lan_network = config.lan.ip.rsplit('.', 1)[0] + '.0/' + str(config.lan.netmask)
            if enable_wan_ssh:
                lines.append('/ip service set ssh disabled=no')
            else:
                lines.append(f'/ip service set ssh address={lan_network} disabled=no')

        # Disable unused services
        if config.security and config.security.disable_unused_services:
            lines.append('/ip service set telnet disabled=yes')
            lines.append('/ip service set ftp disabled=yes')
            lines.append('/ip service set www disabled=yes')
            lines.append('/ip service set api disabled=yes')
            lines.append('/ip service set api-ssl disabled=yes')
        lines.append("")

        # ============================================================
        # MAC DISCOVERY (LAN Only for Security)
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# MAC DISCOVERY (LAN Only)")
        lines.append("# " + "=" * 60)

        if enable_mac_discovery_lan and config.lan:
            lines.append(':do { /interface list add name=LAN } on-error={}')
            lines.append(f':do {{ /interface list member add list=LAN interface={bridge_name} }} on-error={{}}')
            lines.append('/tool mac-server set allowed-interface-list=LAN')
            lines.append('/tool mac-server mac-winbox set allowed-interface-list=LAN')
            lines.append('/tool mac-server ping set enabled=yes')
            lines.append('/ip neighbor discovery-settings set discover-interface-list=LAN')
        else:
            lines.append('/tool mac-server set allowed-interface-list=none')
            lines.append('/tool mac-server mac-winbox set allowed-interface-list=none')
            lines.append('/tool mac-server ping set enabled=no')
            lines.append('/ip neighbor discovery-settings set discover-interface-list=none')
        lines.append("")

        # ============================================================
        # BANDWIDTH TEST SERVER (Disable)
        # ============================================================
        mikrotik_cfg = config.mikrotik_config or {}
        if not mikrotik_cfg.get('bandwidth_test', False):
            lines.append("# Disable bandwidth test server")
            lines.append('/tool bandwidth-server set enabled=no')
            lines.append("")

        # ============================================================
        # ADMIN USER
        # ============================================================
        if config.security:
            lines.append("# " + "=" * 60)
            lines.append("# ADMIN USER")
            lines.append("# " + "=" * 60)
            # Use set to update existing admin, with fallback to add
            lines.append(f':do {{ /user set admin password="{config.security.admin_password}" }} on-error={{ /user add name=admin password="{config.security.admin_password}" group=full }}')
            lines.append("")

        # ============================================================
        # FOOTER
        # ============================================================
        lines.append("# " + "=" * 60)
        lines.append("# CONFIGURATION COMPLETE")
        lines.append("# " + "=" * 60)
        lines.append("# Deployment checklist:")
        lines.append("# 1. Factory reset router, remove default config when prompted")
        lines.append("# 2. Upload this file and run: /import file-name=router.rsc")
        lines.append("# 3. Reconnect to LAN IP with new password")
        lines.append("# 4. Connect WAN port to ISP")
        lines.append("# 5. Verify internet connectivity")

        return "\n".join(lines)

    def _generate_wireless_script(self, config: NetworkConfig) -> str:
        """Generate wireless configuration"""
        lines = []

        lines.append(f"# ===== Wireless Configuration for {config.customer.name} =====")
        lines.append("")

        for idx, wireless in enumerate(config.wireless, 1):
            wlan_interface = f"wlan{idx}"

            if wireless.mode == "wifi6":
                # Modern /interface wifi
                lines.append(f"# WiFi 6 Configuration - {wireless.ssid}")
                lines.append(f"/interface wifi set {wlan_interface} disabled=no")
                lines.append(f"/interface wifi configuration add name=cfg-{wireless.ssid} ssid={self._quote(wireless.ssid)} country={wireless.country}")
                lines.append(f"/interface wifi security add name=sec-{wireless.ssid} authentication-types=wpa2-psk,wpa3-psk passphrase={self._quote(wireless.password)}")
                lines.append(f"/interface wifi set {wlan_interface} configuration=cfg-{wireless.ssid} security=sec-{wireless.ssid}")
            else:
                # Legacy /interface wireless
                lines.append(f"# Legacy Wireless Configuration - {wireless.ssid}")
                lines.append(f"/interface wireless security-profiles add name=sec-{wireless.ssid} authentication-types=wpa2-psk wpa2-pre-shared-key={self._quote(wireless.password)}")
                lines.append(f"/interface wireless set {wlan_interface} disabled=no mode=ap-bridge band={wireless.band} channel-width={wireless.channel_width} ssid={self._quote(wireless.ssid)} country={wireless.country} security-profile=sec-{wireless.ssid}")

            # VLAN tagging if specified
            if wireless.vlan:
                lines.append(f"/interface bridge vlan add bridge={config.lan.interface} tagged={wlan_interface} vlan-ids={wireless.vlan}")

            # Guest isolation
            if wireless.guest_mode:
                lines.append(f"/interface bridge port add bridge={config.lan.interface} interface={wlan_interface} pvid={wireless.vlan or 1} horizon=1 comment=\"Guest isolation\"")

            lines.append("")

        return "\n".join(lines)

    def _quote(self, value: str) -> str:
        """Quote value for RouterOS CLI"""
        s = str(value)
        return '"' + s.replace('"', r'\"') + '"'
