"""
MikroTik RouterOS configuration generator.

Based on the original 462-line script from legacy/mikrotik/config_builder_original.py
"""

from typing import Dict, List
from pathlib import Path
import sys

# Add parent directories to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from vendors.base import VendorGenerator
from core.models import NetworkConfig
from core.validators import IPValidator


class MikroTikGenerator(VendorGenerator):
    """MikroTik RouterOS script generator"""

    vendor_name = "mikrotik"
    supported_features = [
        "routing", "firewall", "nat", "vpn_ipsec", "vpn_wireguard",
        "wireless_legacy", "wireless_wifi6", "vlan", "dhcp", "qos"
    ]

    def validate_config(self, config: NetworkConfig) -> List[str]:
        """MikroTik-specific validation"""
        errors = []

        # TODO: Add MikroTik-specific validation
        # - Check if device model supports requested features
        # - Validate RouterOS version requirements
        # - Check wireless mode compatibility

        return errors

    def generate_config(self, config: NetworkConfig) -> Dict[str, str]:
        """Generate RouterOS .rsc scripts"""
        scripts = {}

        # Generate main router script
        if config.deployment_type.value in ['router_only', 'router_and_ap']:
            scripts["router.rsc"] = self._generate_router_script(config)

        # Generate wireless script if needed
        if config.wireless and config.deployment_type.value in ['ap_only', 'router_and_ap']:
            scripts["wireless.rsc"] = self._generate_wireless_script(config)

        return scripts

    def _generate_router_script(self, config: NetworkConfig) -> str:
        """Generate main router configuration"""
        lines = []

        # Header
        lines.append(f"# ===== {config.customer.name} | {config.customer.site} | {config.device_model} =====")
        lines.append(f"# Generated by Multi-Vendor Network Config Builder")
        lines.append(f"# Vendor: MikroTik RouterOS")
        lines.append("")

        # WAN Configuration
        if config.wan:
            lines.append("# WAN Configuration")
            if config.wan.mode == "static":
                lines.append(f"/ip address add address={config.wan.ip}/{config.wan.netmask} interface={config.wan.interface}")
                lines.append(f"/ip route add gateway={config.wan.gateway}")
            elif config.wan.mode == "dhcp":
                lines.append(f"/ip dhcp-client add interface={config.wan.interface} disabled=no")
            lines.append("")

        # LAN Configuration
        if config.lan:
            lines.append("# LAN Configuration")
            lines.append(f"/interface bridge add name={config.lan.interface}")
            lines.append(f"/ip address add address={config.lan.ip}/{config.lan.netmask} interface={config.lan.interface}")
            lines.append("")

            # DHCP Server
            if config.lan.dhcp and config.lan.dhcp.enabled:
                lines.append("# DHCP Server")
                lines.append(f"/ip pool add name=lan-pool ranges={config.lan.dhcp.pool_start}-{config.lan.dhcp.pool_end}")
                lines.append(f"/ip dhcp-server add name=lan-dhcp interface={config.lan.interface} address-pool=lan-pool lease-time={config.lan.dhcp.lease_time} disabled=no")

                # DNS servers
                dns_servers = ",".join(config.lan.dhcp.dns_servers) if config.lan.dhcp.dns_servers else "8.8.8.8,8.8.4.4"
                lan_subnet = f"{config.lan.ip}/{config.lan.netmask}"
                lines.append(f"/ip dhcp-server network add address={lan_subnet} gateway={config.lan.ip} dns-server={dns_servers}")
                lines.append("")

        # VLANs
        if config.vlans:
            lines.append("# VLAN Configuration")
            for vlan in config.vlans:
                lines.append(f"/interface vlan add name=vlan{vlan.id} vlan-id={vlan.id} interface={config.lan.interface} comment=\"{vlan.name}\"")

                # VLAN IP address
                subnet_parts = vlan.subnet.split('/')
                if len(subnet_parts) == 2:
                    vlan_ip = subnet_parts[0].rsplit('.', 1)[0] + '.1'  # Use .1 as gateway
                    lines.append(f"/ip address add address={vlan_ip}/{subnet_parts[1]} interface=vlan{vlan.id}")

                # VLAN DHCP
                if vlan.dhcp and vlan.dhcp_config:
                    lines.append(f"/ip pool add name=vlan{vlan.id}-pool ranges={vlan.dhcp_config.pool_start}-{vlan.dhcp_config.pool_end}")
                    lines.append(f"/ip dhcp-server add name=vlan{vlan.id}-dhcp interface=vlan{vlan.id} address-pool=vlan{vlan.id}-pool lease-time={vlan.dhcp_config.lease_time} disabled=no")
                    lines.append(f"/ip dhcp-server network add address={vlan.subnet} gateway={vlan_ip}")

            lines.append("")

        # NAT
        if config.wan and config.lan:
            lines.append("# NAT (Masquerade)")
            lines.append(f"/ip firewall nat add chain=srcnat out-interface={config.wan.interface} action=masquerade comment=\"NAT LAN to WAN\"")
            lines.append("")

        # Port Forwarding
        if config.port_forwards:
            lines.append("# Port Forwarding")
            for pf in config.port_forwards:
                if pf.enabled:
                    lines.append(f"/ip firewall nat add chain=dstnat in-interface={config.wan.interface} protocol={pf.protocol} dst-port={pf.external_port} action=dst-nat to-addresses={pf.internal_ip} to-ports={pf.internal_port} comment=\"{pf.name}\"")
                    lines.append(f"/ip firewall filter add chain=forward in-interface={config.wan.interface} protocol={pf.protocol} dst-address={pf.internal_ip} dst-port={pf.internal_port} connection-nat-state=dstnat action=accept comment=\"Allow {pf.name}\"")
            lines.append("")

        # Security Hardening
        if config.security:
            lines.append("# Security Hardening")

            # Admin user
            lines.append(f"/user add name={self._quote(config.security.admin_username)} password={self._quote(config.security.admin_password)} group=full disabled=no")

            # Service restrictions
            allowed_ips = ",".join(config.security.allowed_management_ips) if config.security.allowed_management_ips else "0.0.0.0/0"

            # Get MikroTik-specific settings
            mikrotik_cfg = config.mikrotik_config or {}
            enable_winbox = mikrotik_cfg.get('enable_winbox', True)
            enable_ssh = mikrotik_cfg.get('enable_ssh', True)

            if enable_winbox:
                lines.append(f"/ip service set winbox address={allowed_ips} disabled=no")
            else:
                lines.append("/ip service set winbox disabled=yes")

            if enable_ssh:
                lines.append(f"/ip service set ssh address={allowed_ips} disabled=no")
            else:
                lines.append("/ip service set ssh disabled=yes")

            # Disable unused services
            if config.security.disable_unused_services:
                for svc in ['telnet', 'ftp', 'www', 'api', 'api-ssl']:
                    lines.append(f"/ip service set {svc} disabled=yes")

            # Disable MAC access & neighbor discovery
            lines.append("/tool mac-server set allowed-interface-list=none")
            lines.append("/tool mac-server mac-winbox set allowed-interface-list=none")
            lines.append("/tool mac-server ping set enabled=no")
            lines.append("/ip neighbor discovery-settings set discover-interface-list=none")
            lines.append("")

        # MikroTik-specific features
        mikrotik_cfg = config.mikrotik_config or {}

        if mikrotik_cfg.get('bandwidth_test', False):
            lines.append("# Bandwidth Test Server")
            lines.append("/tool bandwidth-server set enabled=yes")
            lines.append("")

        if mikrotik_cfg.get('stun_port', False):
            lines.append("# STUN Configuration")
            lines.append("# Add STUN forwarding rules here")
            lines.append("")

        return "\n".join(lines)

    def _generate_wireless_script(self, config: NetworkConfig) -> str:
        """Generate wireless configuration"""
        lines = []

        lines.append(f"# ===== Wireless Configuration for {config.customer.name} =====")
        lines.append("")

        for idx, wireless in enumerate(config.wireless, 1):
            wlan_interface = f"wlan{idx}"

            if wireless.mode == "wifi6":
                # Modern /interface wifi
                lines.append(f"# WiFi 6 Configuration - {wireless.ssid}")
                lines.append(f"/interface wifi set {wlan_interface} disabled=no")
                lines.append(f"/interface wifi configuration add name=cfg-{wireless.ssid} ssid={self._quote(wireless.ssid)} country={wireless.country}")
                lines.append(f"/interface wifi security add name=sec-{wireless.ssid} authentication-types=wpa2-psk,wpa3-psk passphrase={self._quote(wireless.password)}")
                lines.append(f"/interface wifi set {wlan_interface} configuration=cfg-{wireless.ssid} security=sec-{wireless.ssid}")
            else:
                # Legacy /interface wireless
                lines.append(f"# Legacy Wireless Configuration - {wireless.ssid}")
                lines.append(f"/interface wireless security-profiles add name=sec-{wireless.ssid} authentication-types=wpa2-psk wpa2-pre-shared-key={self._quote(wireless.password)}")
                lines.append(f"/interface wireless set {wlan_interface} disabled=no mode=ap-bridge band={wireless.band} channel-width={wireless.channel_width} ssid={self._quote(wireless.ssid)} country={wireless.country} security-profile=sec-{wireless.ssid}")

            # VLAN tagging if specified
            if wireless.vlan:
                lines.append(f"/interface bridge vlan add bridge={config.lan.interface} tagged={wlan_interface} vlan-ids={wireless.vlan}")

            # Guest isolation
            if wireless.guest_mode:
                lines.append(f"/interface bridge port add bridge={config.lan.interface} interface={wlan_interface} pvid={wireless.vlan or 1} horizon=1 comment=\"Guest isolation\"")

            lines.append("")

        return "\n".join(lines)

    def _quote(self, value: str) -> str:
        """Quote value for RouterOS CLI"""
        s = str(value)
        return '"' + s.replace('"', r'\"') + '"'
