# ===== DC Lawn | 16520 Gaineswood Dr N, Fairhope, AL 36532-5164 | MikroTik Router =====
# Generated by Multi-Vendor Network Config Builder
# Vendor: MikroTik RouterOS

# WAN Configuration
/ip address add address=142.190.216.66/30 interface=ether1
/ip route add gateway=142.190.216.65

# LAN Configuration
/interface bridge add name=bridge-lan
/ip address add address=10.54.0.1/24 interface=bridge-lan

# DHCP Server
/ip pool add name=lan-pool ranges=10.54.0.100-10.54.0.200
/ip dhcp-server add name=lan-dhcp interface=bridge-lan address-pool=lan-pool lease-time=24h disabled=no
/ip dhcp-server network add address=10.54.0.1/24 gateway=10.54.0.1 dns-server=142.190.111.111,142.190.222.222

# NAT (Masquerade)
/ip firewall nat add chain=srcnat out-interface=ether1 action=masquerade comment="NAT LAN to WAN"

# Security Hardening
/user add name="admin" password="ChangeMe@205922!" group=full disabled=no
/ip service set winbox address=10.54.0.0/24,142.190.216.64/30 disabled=no
/ip service set ssh address=10.54.0.0/24,142.190.216.64/30 disabled=no
/ip service set telnet disabled=yes
/ip service set ftp disabled=yes
/ip service set www disabled=yes
/ip service set api disabled=yes
/ip service set api-ssl disabled=yes
/tool mac-server set allowed-interface-list=none
/tool mac-server mac-winbox set allowed-interface-list=none
/tool mac-server ping set enabled=no
/ip neighbor discovery-settings set discover-interface-list=none
